### ISSUE TITLE
Is the README out of date? 

### ISSUE THREAD

**Issue by AlexChesters** [connected-tv/connected-tv-app-monitor#1]
See the following line
```
git clone git@github.com:johnbeech/connected-tv-app-monitor.git
```

Should this be
```
git clone git@github.com:connected-tv/connected-tv-app-monitor.git
```

**Comment by subsidel** [comment]
The repo used to be "owned" by @johnbeech, but was transferred to the connected-tv github org, and through the magic of github, that URI should work, however, I do think it is slightly confusing.
